### ISSUE TITLE
Request to delete unused tables when transitioning to ccdb 2.0

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/ccdb#65]
There are several ccdb tables which may have some values in but have *never* been used by the sim/recon code. Can these be deleted when the new database is made for ccdb 2.0, please?  I can supply a list.

**Comment by sdobbs** [comment]
See #12

**Comment by DraTeots** [comment]
Migration to 2.0 might be a good point (because we will have a backup database) to do a real cleanup besides just deprecating the data. But I would ask for collaboration discussion and agreement about that. 

About removing/deprecating stuff:

https://github.com/JeffersonLab/ccdb/wiki/CCDB-CLI#deleting-objects

While CCDB discourages to delete anything. Instead, one can deprecate tables, directories or variations, which are old and not used anymore. Deprecation removes tables/directories from listings (e.g. ls command) but if old code will request the constants, they will be available.

There are still cases, when removing something might be required:

- It is possible to make a typo/mistake when creating a table/variation
- On early development stage (introducing new constants and writing code, that uses it) it might be beneficial to recreate something (e.g. a table with different set of rows). CCDB warning: this already might lead to trouble(!) but in many cases with playground SQL it is OK.
- For all other cases deletion is highly not recommended! Treat CCDB as a logbook - calibration data logbook. But still removing stuff is technically possible.

rm - command shell be used with common flags -d, -t, -v, -a to remove a directory, table, variation or assignment.

    Directory/table/variation must be empty to be removed. Which means, one has to first delete all assignments from table to remove table, remove all tables to remove a directory, etc.

**Comment by sdobbs** [comment]
I agree we should not delete things.

Is deprecation actually implemented in the current version of CCDB though?

**Comment by markito3** [comment]
Given today's events, I am not eager to try table deletion again. Closing this one.

**Comment by DraTeots** [comment]
It is implemented in new SQL schema (for 2.0)
