### ISSUE TITLE
ccdb -i no go, ccdb 2.00

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#78]
This is on Fedora 33.
- checkout ccdb on the 2.00 branch (8b5a92d)
- source ccdb/environment.bash
- ccdb -i complains about sqlalchemy

```
$ ccdb -i
Traceback (most recent call last):
  File "/home/marki/git/ccdb/bin/ccdb", line 4, in <module>
    import ccdb
  File "/home/marki/git/ccdb/python/ccdb/__init__.py", line 24, in <module>
    from .provider import AlchemyProvider
  File "/home/marki/git/ccdb/python/ccdb/provider.py", line 12, in <module>
    from .model import CcdbSchemaVersion
  File "/home/marki/git/ccdb/python/ccdb/model.py", line 4, in <module>
    from sqlalchemy import text
ImportError: No module named sqlalchemy
```
Am I missing a Python module?

**Comment by DraTeots** [comment]
Workaround is to 

```bash
pip install --user --upgrade sqlalchemy pymysql six 
```

To check and to fix this

python/ccdb/__init__.py#55

Initially CCDB shipped the libraries with it. In order to put CCDB on pypi (so one could do ```pip install ccdb```) those libraries should be used from system. The check happens in python/ccdb/__init__.py and `sys.path.append` happens to use embedded libraries. This should be checked (and fixed) to solve this issue

**Comment by DraTeots** [comment]
Fixed in v2-main
