### ISSUE TITLE
rcdb sqlalchemy used by ccdb?

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#84]
Not sure where to put this issue. I may be completely transient, but wanted to have it stored somewhere.

Recently had as issue where write operations were hanging on the command line for several minutes before the python stace trace occurred. Find the stace here:

[stack_trace.txt](https://github.com/JeffersonLab/ccdb/files/7033997/stack_trace.txt)

This problem disappeared immediately after the stack trace appeared. No idea what was happening.

**Comment by DraTeots** [comment]
Well... Python uses PYTHONPATH env to find libraries. CCDB looks for external SQLAlchemy and when doesn't find one it uses embedded SQLAlchemy. So most probably RCDB is configured so that PYTHONPATH points to RCDB python folder and then CCDB sees external SQLAlchemy which actually comes from RCDB. 

But they should be fine with this. It is the same SQLAlchemy library
